### PR TITLE
Add a Cons trait and implement First, Second, Third in terms of it.

### PR DESCRIPTION
**Pull request by Stebalien**
E.g., `second` is `seq.uncons().1.uncons().0`.

@bluss,

Do you think this is worth it or is it too confusing. Also, is it worth it to
keep the `First`, `Second`, and `Third` definitions?

### CODE REVIEW

**Comment by bluss** [comment]
Keep them, absolutely. I would not want to read or write code that says `self.uncons().1.uncons().0`.

**Comment by Stebalien** [comment]
Keep the functions, obviously. I'm wondering if we should keep the traits or just define these functions in terms of Cons.

**Comment by bluss** [comment]
Oh! I guess the traits are fine to remove. Do you think user code would use functions like `fn frob<T: First>()` ? Cons suffices for that right now.

**Comment by Stebalien** [comment]
So, I've kept them in for now but completely defined them in terms of `Cons`. There isn't any noticeable performance regression as far as I can tell.

**Pull request merged**
